/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DataAccessObject;
import gerenciarhorarios.Professor;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Rodrigo
 */
public class CadastrarProfessor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarProfessores
     */
    public CadastrarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomeProfessor = new javax.swing.JTextField();
        jLabelNomeProfessor = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar professor");

        jTextFieldNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProfessorActionPerformed(evt);
            }
        });
        jTextFieldNomeProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeProfessorKeyPressed(evt);
            }
        });

        jLabelNomeProfessor.setText("Nome completo do professor");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelNomeProfessor)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldNomeProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelNomeProfessor))
                    .addComponent(jTextFieldNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProfessorActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        String nomeProfessor = jTextFieldNomeProfessor.getText();

        nomeProfessor = nomeProfessor.trim().replaceAll("\\s+", " "); //Remover espaços em branco
        //no início e final da string, e tratar espaços duplicados no meio da string.
        
        //Tratar casos em que o campo Nome completo do professor está vazio.
        if (nomeProfessor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'Nome completo do "
                    + "professor' não pode ser vazio", "Campo vazio", JOptionPane.ERROR_MESSAGE);
            jTextFieldNomeProfessor.requestFocus();
            return;
        }

        Professor professores = new Professor(nomeProfessor);

        DataAccessObject.abrirConexao();
        DataAccessObject.insert(professores); //Inserir no banco de dados.
        DataAccessObject.fecharConexao();

        JOptionPane.showMessageDialog(null, "Professor cadastrado com sucesso!");
        jTextFieldNomeProfessor.setText("");
        jTextFieldNomeProfessor.requestFocus();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jTextFieldNomeProfessorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeProfessorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nomeProfessor = jTextFieldNomeProfessor.getText();

            nomeProfessor = nomeProfessor.trim().replaceAll("\\s+", " "); //Remover espaços em branco
        //no início e final da string, e tratar espaços duplicados no meio da string.

            //Tratar casos em que o campo Nome completo do professor está vazio.
            if (nomeProfessor.isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo 'Nome completo do "
                        + "professor' não pode ser vazio", "Campo vazio", JOptionPane.ERROR_MESSAGE);
                jTextFieldNomeProfessor.requestFocus();
                return;
            }

            Professor professores = new Professor(nomeProfessor);

            DataAccessObject.abrirConexao();
            DataAccessObject.insert(professores); //Inserir no banco de dados.
            DataAccessObject.fecharConexao();

            JOptionPane.showMessageDialog(null, "Professor cadastrado com sucesso!");
            jTextFieldNomeProfessor.setText("");
            jTextFieldNomeProfessor.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldNomeProfessorKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelNomeProfessor;
    private javax.swing.JTextField jTextFieldNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
