/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DataAccessObject;
import gerenciarhorarios.Turma;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class HabilitarDesabilitarRestricoesTurma extends javax.swing.JInternalFrame {

    ArrayList<Turma> turmas = new ArrayList<>();
    Turma turma = null;

    /**
     * Creates new form HabilitarDesabilitarRestricoesTurma
     */
    public HabilitarDesabilitarRestricoesTurma() {
        initComponents();

        //Adicionar os botões habilitar e desabilitar do janelamento de disciplinas
        //a um mesmo grupo.
        buttonGroupJanelamentoDisciplinas.add(jRadioButtonJanelamentoDisciplinasHabilitar);
        buttonGroupJanelamentoDisciplinas.add(jRadioButtonJanelamentoDisciplinasDesabilitar);

        //Adicionar os botões habilitar, desabilitar e desconsiderar das aulas geminadas
        //a um mesmo grupo.
        buttonGroupAulasGeminadas.add(jRadioButtonAulasGeminadasHabilitar);
        buttonGroupAulasGeminadas.add(jRadioButtonAulasGeminadasDesabilitar);
        buttonGroupAulasGeminadas.add(jRadioButtonAulasGeminadasDesconsiderar);

        turmas = DataAccessObject.getTurmas();

        //Adicionar as turmas ao jComboBox.
        for (int i = 0; i < turmas.size(); i++) {
            if (turmas.get(i).getNivelEnsino().equals("Superior")) {
                jComboBoxTurmas.addItem("Curso: " + turmas.get(i).getCurso() + " | Nível de ensino: "
                        + turmas.get(i).getNivelEnsino() + " | Turma: " + turmas.get(i).getNome()
                        + " | Semestre: " + turmas.get(i).getAno() + " | Turno: " + turmas.get(i).getTurno());
            } else {
                jComboBoxTurmas.addItem("Nível de ensino: "
                        + turmas.get(i).getNivelEnsino() + " | Turma: " + turmas.get(i).getNome()
                        + " | Série: " + turmas.get(i).getAno() + " | Turno: " + turmas.get(i).getTurno());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJanelamentoDisciplinas = new javax.swing.ButtonGroup();
        buttonGroupAulasGeminadas = new javax.swing.ButtonGroup();
        jLabelJanelamentoDisciplinas = new javax.swing.JLabel();
        jLabelTurma = new javax.swing.JLabel();
        jComboBoxTurmas = new javax.swing.JComboBox<>();
        jButtonSelecionar = new javax.swing.JButton();
        jRadioButtonJanelamentoDisciplinasHabilitar = new javax.swing.JRadioButton();
        jRadioButtonJanelamentoDisciplinasDesabilitar = new javax.swing.JRadioButton();
        jLabelDiasSemana = new javax.swing.JLabel();
        jCheckBoxSegunda = new javax.swing.JCheckBox();
        jCheckBoxTerca = new javax.swing.JCheckBox();
        jCheckBoxQuarta = new javax.swing.JCheckBox();
        jCheckBoxQuinta = new javax.swing.JCheckBox();
        jCheckBoxSexta = new javax.swing.JCheckBox();
        jCheckBoxSabado = new javax.swing.JCheckBox();
        jLabelAulasGeminadas = new javax.swing.JLabel();
        jRadioButtonAulasGeminadasHabilitar = new javax.swing.JRadioButton();
        jRadioButtonAulasGeminadasDesabilitar = new javax.swing.JRadioButton();
        jRadioButtonAulasGeminadasDesconsiderar = new javax.swing.JRadioButton();
        jButtonConfirmar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabelJanelamentoDisciplinas.setText("Janelamento entre disciplinas");

        jLabelTurma.setText("Turma");

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jRadioButtonJanelamentoDisciplinasHabilitar.setText("Permitir");
        jRadioButtonJanelamentoDisciplinasHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJanelamentoDisciplinasHabilitarActionPerformed(evt);
            }
        });

        jRadioButtonJanelamentoDisciplinasDesabilitar.setText("Não permitir");

        jLabelDiasSemana.setText("Dias da semana (marcar para habilitar)");

        jCheckBoxSegunda.setText("Segunda");

        jCheckBoxTerca.setText("Terça");

        jCheckBoxQuarta.setText("Quarta");

        jCheckBoxQuinta.setText("Quinta");

        jCheckBoxSexta.setText("Sexta");

        jCheckBoxSabado.setText("Sábado");

        jLabelAulasGeminadas.setText("Aulas geminadas");

        jRadioButtonAulasGeminadasHabilitar.setText("Habilitar");

        jRadioButtonAulasGeminadasDesabilitar.setText("Desabilitar");

        jRadioButtonAulasGeminadasDesconsiderar.setText("Desconsiderar");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTurmas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelecionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonAulasGeminadasHabilitar)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAulasGeminadasDesabilitar)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAulasGeminadasDesconsiderar))
                            .addComponent(jLabelJanelamentoDisciplinas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonJanelamentoDisciplinasHabilitar)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonJanelamentoDisciplinasDesabilitar))
                            .addComponent(jLabelDiasSemana)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxSegunda)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxTerca)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxQuarta)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxQuinta)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxSexta)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxSabado))
                            .addComponent(jLabelAulasGeminadas))
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurma)
                    .addComponent(jComboBoxTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionar))
                .addGap(18, 18, 18)
                .addComponent(jLabelJanelamentoDisciplinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonJanelamentoDisciplinasHabilitar)
                    .addComponent(jRadioButtonJanelamentoDisciplinasDesabilitar))
                .addGap(18, 18, 18)
                .addComponent(jLabelDiasSemana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSegunda)
                    .addComponent(jCheckBoxTerca)
                    .addComponent(jCheckBoxQuarta)
                    .addComponent(jCheckBoxQuinta)
                    .addComponent(jCheckBoxSexta)
                    .addComponent(jCheckBoxSabado))
                .addGap(18, 18, 18)
                .addComponent(jLabelAulasGeminadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAulasGeminadasHabilitar)
                    .addComponent(jRadioButtonAulasGeminadasDesabilitar)
                    .addComponent(jRadioButtonAulasGeminadasDesconsiderar))
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        DataAccessObject.abrirConexao();

        turma = turmas.get(jComboBoxTurmas.getSelectedIndex()); //Turma selecionada.

        //Inicializar opção de janelamento de disciplinas.
        if (turma.getJanelamentoDisciplinas()) {
            //Se o janelamento de disciplinas estiver ativo.
            //Marcar botão Habilitar.
            jRadioButtonJanelamentoDisciplinasHabilitar.setSelected(true);
        } else {
            //Marcar botão desabilitar.
            jRadioButtonJanelamentoDisciplinasDesabilitar.setSelected(true);
        }

        //Inicializar dias da semana.
        for (int i = 0; i < 6; i++) {
            if (turma.getDiasSemana()[i] == '1') {
                //Se estiver disponível, marcar.
                switch (i) {
                    case 0:
                        //Segunda
                        jCheckBoxSegunda.setSelected(true);
                        break;
                    case 1:
                        //Terça
                        jCheckBoxTerca.setSelected(true);
                        break;
                    case 2:
                        //Quarta
                        jCheckBoxQuarta.setSelected(true);
                        break;
                    case 3:
                        //Quinta
                        jCheckBoxQuinta.setSelected(true);
                        break;
                    case 4:
                        //Sexta
                        jCheckBoxSexta.setSelected(true);
                        break;
                    case 5:
                        //Sábado
                        jCheckBoxSabado.setSelected(true);
                        break;
                }
            } else {
                //Desmarcar
                switch (i) {
                    case 0:
                        //Segunda
                        jCheckBoxSegunda.setSelected(false);
                        break;
                    case 1:
                        //Terça
                        jCheckBoxTerca.setSelected(false);
                        break;
                    case 2:
                        //Quarta
                        jCheckBoxQuarta.setSelected(false);
                        break;
                    case 3:
                        //Quinta
                        jCheckBoxQuinta.setSelected(false);
                        break;
                    case 4:
                        //Sexta
                        jCheckBoxSexta.setSelected(false);
                        break;
                    case 5:
                        //Sábado
                        jCheckBoxSabado.setSelected(false);
                        break;
                }
            }
        }

        //Inicializar opção de aulas geminadas.
        if (turma.getAulasGeminadas()) {
            //Se as aulas geminadas estiverem habilitadas.
            //Marcar botão Habilitar.
            jRadioButtonAulasGeminadasHabilitar.setSelected(true);
        } else if (turma.getSemAulasGeminadas()) {
            //Se estiver desabilitado.
            //Marcar opção Desabilitar.
            jRadioButtonAulasGeminadasDesabilitar.setSelected(true);
        } else {
            //Se não levar as aulas geminadas em consideração, ou seja, não
            //importar se possui ou não aulas geminadas.
            //Marcar opção Desconsiderar.
            jRadioButtonAulasGeminadasDesconsiderar.setSelected(true);
        }

        DataAccessObject.fecharConexao();
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        DataAccessObject.abrirConexao();

        //Atualizar janelamento de disciplinas na turma.
        if (jRadioButtonJanelamentoDisciplinasHabilitar.isSelected()) {
            //Opção habilitar selecionada.
            //Atualizar na turma.
            turma.setJanelamentoDisciplinas(true);
        } else {
            //Opção desabilitar selecionada.
            turma.setJanelamentoDisciplinas(false);
        }

        //Atualizar dias da semana na turma.
        char[] diasSemana = new char[6];

        //Segunda
        if (jCheckBoxSegunda.isSelected()) {
            diasSemana[0] = '1';
        } else {
            diasSemana[0] = '0';
        }
        //Terça
        if (jCheckBoxTerca.isSelected()) {
            diasSemana[1] = '1';
        } else {
            diasSemana[1] = '0';
        }
        //Quarta
        if (jCheckBoxQuarta.isSelected()) {
            diasSemana[2] = '1';
        } else {
            diasSemana[2] = '0';
        }
        //Quinta
        if (jCheckBoxQuinta.isSelected()) {
            diasSemana[3] = '1';
        } else {
            diasSemana[3] = '0';
        }
        //Sexta
        if (jCheckBoxSexta.isSelected()) {
            diasSemana[4] = '1';
        } else {
            diasSemana[4] = '0';
        }
        //Sábado
        if (jCheckBoxSabado.isSelected()) {
            diasSemana[5] = '1';
        } else {
            diasSemana[5] = '0';
        }

        turma.setDiasSemana(diasSemana);

        //Se desconsiderar estiver habilitado, aulas geminadas e sem aulas
        //geminadas = false.
        if (jRadioButtonAulasGeminadasDesconsiderar.isSelected()) {
            turma.setAulasGeminadas(false);
            turma.setSemAulasGeminadas(false);
        } else {
            //Atualizar aulas geminadas na turma.
            if (jRadioButtonAulasGeminadasHabilitar.isSelected()) {
                turma.setAulasGeminadas(true);
            } else {
                turma.setAulasGeminadas(false);
            }

            //Atualizar sem aulas geminadas na turma.
            if (jRadioButtonAulasGeminadasDesabilitar.isSelected()) {
                turma.setSemAulasGeminadas(true);
            } else {
                turma.setSemAulasGeminadas(false);
            }
        }
        
        DataAccessObject.update(turma);
        JOptionPane.showMessageDialog(null, "Restrições atualizadas com sucesso!");

        DataAccessObject.fecharConexao();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jRadioButtonJanelamentoDisciplinasHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJanelamentoDisciplinasHabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonJanelamentoDisciplinasHabilitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAulasGeminadas;
    private javax.swing.ButtonGroup buttonGroupJanelamentoDisciplinas;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JCheckBox jCheckBoxQuarta;
    private javax.swing.JCheckBox jCheckBoxQuinta;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxSegunda;
    private javax.swing.JCheckBox jCheckBoxSexta;
    private javax.swing.JCheckBox jCheckBoxTerca;
    private javax.swing.JComboBox<String> jComboBoxTurmas;
    private javax.swing.JLabel jLabelAulasGeminadas;
    private javax.swing.JLabel jLabelDiasSemana;
    private javax.swing.JLabel jLabelJanelamentoDisciplinas;
    private javax.swing.JLabel jLabelTurma;
    private javax.swing.JRadioButton jRadioButtonAulasGeminadasDesabilitar;
    private javax.swing.JRadioButton jRadioButtonAulasGeminadasDesconsiderar;
    private javax.swing.JRadioButton jRadioButtonAulasGeminadasHabilitar;
    private javax.swing.JRadioButton jRadioButtonJanelamentoDisciplinasDesabilitar;
    private javax.swing.JRadioButton jRadioButtonJanelamentoDisciplinasHabilitar;
    // End of variables declaration//GEN-END:variables
}
