/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DataAccessObject;
import gerenciarhorarios.Disciplina;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author rodrigo
 */
public class ListarDisciplinas extends javax.swing.JInternalFrame {
    ArrayList<Disciplina> disciplinas = null; //Lista das disciplinas do banco de dados.
    DefaultListModel listModel = new DefaultListModel(); //Modelo para o JList.
    
    /**
     * Creates new form ListarDisciplinas
     */
    public ListarDisciplinas() {
        initComponents();
        
        jListDisciplinas.setModel(listModel);

        DataAccessObject.abrirConexao();
        disciplinas = DataAccessObject.getDisciplinas();

        for (int i = 0; i < disciplinas.size(); i++) {
            listModel.addElement(disciplinas.get(i).getNome() + " (Professor(a): "
                    + DataAccessObject.getProfessorByID(disciplinas.get(i).getIdProfessor()).getNome() + ")");
        }
        DataAccessObject.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListDisciplinas = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listar disciplinas");

        jScrollPane1.setViewportView(jListDisciplinas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListDisciplinas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
