/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DataAccessObject;
import gerenciarhorarios.Aula;
import gerenciarhorarios.Disciplina;
import gerenciarhorarios.Turma;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Rodrigo
 */
public class ListarAulasConjuntas extends javax.swing.JInternalFrame {

    ArrayList<Turma> turmas = new ArrayList<>();

    DefaultListModel listModel = new DefaultListModel(); //Modelo para o JList.

    /**
     * Creates new form ListarAulasConjuntas
     */
    public ListarAulasConjuntas() {
        initComponents();

        jListTurmas.setModel(listModel);

        ArrayList<Aula> aulas = DataAccessObject.getAulas();

        for (int i = 0; i < aulas.size(); i++) {
            if (aulas.get(i).getIDTurmaConjunta() != 0) {
                //Possui turma conjunta.
                //Adicionar ao jListTurmas.
                Turma turma = DataAccessObject.getTurmaByID(aulas.get(i).getIDTurma());
                Disciplina disciplina = DataAccessObject.getDisciplinaByID(aulas.get(i).getIDDisciplina());
                Turma turmaConjunta = DataAccessObject.getTurmaByID(aulas.get(i).getIDTurmaConjunta());

                if (turma.getNivelEnsino().equals("Superior")) {
                    //Ensino superior.
                    listModel.addElement("Curso: " + turma.getCurso() + " | Nível de ensino: "
                            + turma.getNivelEnsino() + " | Turma: " + turma.getNome()
                            + " | Semestre: " + turma.getAno() + " | Turno: " + turma.getTurno()
                            + " | Disciplina: " + disciplina.getNome() + " || Turma conjunta: "
                            + turmaConjunta.getNome() + " | Curso: " + turmaConjunta.getCurso() 
                            + " | Semestre: " + turmaConjunta.getAno());
                } else {
                    //Ensino médio ou fundamental.
                    listModel.addElement("Nível de ensino: "
                            + turma.getNivelEnsino() + " | Turma: " + turma.getNome()
                            + " | Série: " + turma.getAno() + " | Turno: " + turma.getTurno() +
                            " | Disciplina: " + disciplina.getNome() + " || Turma conjunta: " +
                            turmaConjunta.getNome() + " | Série: " + turmaConjunta.getAno());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListTurmas = new javax.swing.JList<>();
        jLabelDescricao = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listar aulas conjuntas");

        jScrollPane1.setViewportView(jListTurmas);

        jLabelDescricao.setText("Turmas que possuem turmas conjuntas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDescricao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JList<String> jListTurmas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
